local mapcolor = {r=0, g=0, b=0} -- This gets replaced with the proper color later.
local tilevart = 0 -- Holds the tile_variation template generated by our color.
local sizes = {
    max_size = 4,
    [1] = { weights = {0.085, 0.085, 0.085, 0.085, 0.087, 0.085, 0.065, 0.085, 0.045, 0.045, 0.045, 0.045, 0.005, 0.025, 0.045, 0.045 } },
    [2] = { probability = 0.91, weights = {0.150, 0.150, 0.150, 0.150, 0.018, 0.020, 0.015, 0.025, 0.015, 0.020, 0.025, 0.015, 0.025, 0.025, 0.010, 0.025 }, },
    [4] = { probability = 0.91, weights = {0.100, 0.80, 0.80, 0.100, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01 }, }
}

if settings.startup["color-terrain"].value == "White" then
    mapcolor = {r=230, g=230, b=230}
    tilevart = tile_variations_template(
      "__SingleColorTerrain_Redux__/graphics/hr-white.png", "__base__/graphics/terrain/masks/transition-3.png",
      sizes
    )
end
if settings.startup["color-terrain"].value == "Black" then
    mapcolor = {r=30, g=30, b=30}
    tilevart = tile_variations_template(
        "__SingleColorTerrain_Redux__/graphics/hr-black.png", "__base__/graphics/terrain/masks/transition-3.png",
        sizes
    )
end
if settings.startup["color-terrain"].value == "Green" then
    mapcolor = {r=70, g=170, b=90}
    tilevart = tile_variations_template(
        "__SingleColorTerrain_Redux__/graphics/hr-green.png", "__base__/graphics/terrain/masks/transition-3.png",
        sizes
    )
end
if settings.startup["color-terrain"].value == "Yellow" then
    mapcolor = {r=80, g=180, b=60}
    tilevart = tile_variations_template(
        "__SingleColorTerrain_Redux__/graphics/hr-yellow.png", "__base__/graphics/terrain/masks/transition-3.png",
        sizes
    )
end
if settings.startup["color-terrain"].value == "Blue" then
    mapcolor = {r=0, g=120, b=180}
    tilevart = tile_variations_template(
        "__SingleColorTerrain_Redux__/graphics/hr-blue.png", "__base__/graphics/terrain/masks/transition-3.png",
        sizes
    )
end
if settings.startup["color-terrain"].value == "Red" then
    mapcolor = {r=180, g=30, b=30}
    tilevart = tile_variations_template(
        "__SingleColorTerrain_Redux__/graphics/hr-red.png", "__base__/graphics/terrain/masks/transition-3.png",
        sizes
    )
end
if settings.startup["color-terrain"].value == "Chooser" then
    mapcolor = settings.startup["color-chooser"].value
    tilevart = tile_variations_template(
      "__SingleColorTerrain_Redux__/graphics/hr-sctr-mask.png", "__base__/graphics/terrain/masks/transition-3.png",
        sizes
    )
    data.raw["tile"]["dry-dirt"].tint = mapcolor
    data.raw["tile"]["dirt-1"].tint = mapcolor
    data.raw["tile"]["dirt-2"].tint = mapcolor
    data.raw["tile"]["dirt-3"].tint = mapcolor
    data.raw["tile"]["dirt-4"].tint = mapcolor
    data.raw["tile"]["dirt-5"].tint = mapcolor
    data.raw["tile"]["dirt-6"].tint = mapcolor
    data.raw["tile"]["dirt-7"].tint = mapcolor
    data.raw["tile"]["sand-1"].tint = mapcolor
    data.raw["tile"]["sand-2"].tint = mapcolor
    data.raw["tile"]["sand-3"].tint = mapcolor
    data.raw["tile"]["red-desert-0"].tint = mapcolor
    data.raw["tile"]["red-desert-1"].tint = mapcolor
    data.raw["tile"]["red-desert-2"].tint = mapcolor
    data.raw["tile"]["red-desert-3"].tint = mapcolor
    data.raw["tile"]["grass-2"].tint = mapcolor
    data.raw["tile"]["grass-3"].tint = mapcolor
    data.raw["tile"]["grass-4"].tint = mapcolor
    data.raw["tile"]["grass-1"].tint = mapcolor
end
if settings.startup["color-terrain"].value == "Chooser - Half Bright" then
    mapcolor = settings.startup["color-chooser"].value
    tilevart = tile_variations_template(
      "__SingleColorTerrain_Redux__/graphics/hr-sctr-mask-half.png", "__base__/graphics/terrain/masks/transition-3.png",
        sizes
    )
    data.raw["tile"]["dry-dirt"].tint = mapcolor
    data.raw["tile"]["dirt-1"].tint = mapcolor
    data.raw["tile"]["dirt-2"].tint = mapcolor
    data.raw["tile"]["dirt-3"].tint = mapcolor
    data.raw["tile"]["dirt-4"].tint = mapcolor
    data.raw["tile"]["dirt-5"].tint = mapcolor
    data.raw["tile"]["dirt-6"].tint = mapcolor
    data.raw["tile"]["dirt-7"].tint = mapcolor
    data.raw["tile"]["sand-1"].tint = mapcolor
    data.raw["tile"]["sand-2"].tint = mapcolor
    data.raw["tile"]["sand-3"].tint = mapcolor
    data.raw["tile"]["red-desert-0"].tint = mapcolor
    data.raw["tile"]["red-desert-1"].tint = mapcolor
    data.raw["tile"]["red-desert-2"].tint = mapcolor
    data.raw["tile"]["red-desert-3"].tint = mapcolor
    data.raw["tile"]["grass-2"].tint = mapcolor
    data.raw["tile"]["grass-3"].tint = mapcolor
    data.raw["tile"]["grass-4"].tint = mapcolor
    data.raw["tile"]["grass-1"].tint = mapcolor
end
--log(serpent.block(mapcolor))
-- Default color chooser means we don't want to do any of this.
if not (settings.startup["color-terrain"].value == "Default") then
    -- Set up the terrain tiles to be identical
    data.raw["tile"]["dry-dirt"].variants = tilevart
    data.raw["tile"]["dirt-1"].variants = tilevart
    data.raw["tile"]["dirt-2"].variants = tilevart
    data.raw["tile"]["dirt-3"].variants = tilevart
    data.raw["tile"]["dirt-4"].variants = tilevart
    data.raw["tile"]["dirt-5"].variants = tilevart
    data.raw["tile"]["dirt-6"].variants = tilevart
    data.raw["tile"]["dirt-7"].variants = tilevart
    data.raw["tile"]["sand-1"].variants = tilevart
    data.raw["tile"]["sand-2"].variants = tilevart
    data.raw["tile"]["sand-3"].variants = tilevart
    data.raw["tile"]["red-desert-0"].variants = tilevart
    data.raw["tile"]["red-desert-1"].variants = tilevart
    data.raw["tile"]["red-desert-2"].variants = tilevart
    data.raw["tile"]["red-desert-3"].variants = tilevart
    data.raw["tile"]["grass-2"].variants = tilevart
    data.raw["tile"]["grass-3"].variants = tilevart
    data.raw["tile"]["grass-4"].variants = tilevart
    data.raw["tile"]["grass-1"].variants = tilevart

    -- Set up the map color for every tile to be the chosen map color
    data.raw["tile"]["grass-1"].map_color=mapcolor
    data.raw["tile"]["grass-2"].map_color=mapcolor
    data.raw["tile"]["grass-3"].map_color=mapcolor
    data.raw["tile"]["grass-4"].map_color=mapcolor
    data.raw["tile"]["red-desert-0"].map_color=mapcolor
    data.raw["tile"]["red-desert-1"].map_color=mapcolor
    data.raw["tile"]["red-desert-2"].map_color=mapcolor
    data.raw["tile"]["red-desert-3"].map_color=mapcolor
    data.raw["tile"]["dry-dirt"].map_color=mapcolor
    data.raw["tile"]["dirt-1"].map_color=mapcolor
    data.raw["tile"]["dirt-2"].map_color=mapcolor
    data.raw["tile"]["dirt-3"].map_color=mapcolor
    data.raw["tile"]["dirt-4"].map_color=mapcolor
    data.raw["tile"]["dirt-5"].map_color=mapcolor
    data.raw["tile"]["dirt-6"].map_color=mapcolor
    data.raw["tile"]["dirt-7"].map_color=mapcolor
    data.raw["tile"]["sand-1"].map_color=mapcolor
    data.raw["tile"]["sand-2"].map_color=mapcolor
    data.raw["tile"]["sand-3"].map_color=mapcolor
end

if settings.startup["colorful-machines"].value  then
    data.raw["assembling-machine"]["assembling-machine-1"].animation = {
      layers = {
        {
            filename = "__SingleColorTerrain_Redux__/graphics/entity/assembling-machine-1/hr-assembling-machine-1.png",
            priority="high",
            width = 214,
            height = 226,
            frame_count = 32,
            line_length = 8,
            shift = util.by_pixel(0, 2),
            scale = 0.5
        },
        {
            filename = "__base__/graphics/entity/assembling-machine-1/hr-assembling-machine-1-shadow.png",
            priority="high",
            width = 190,
            height = 165,
            frame_count = 1,
            line_length = 1,
            repeat_count = 32,
            draw_as_shadow = true,
            shift = util.by_pixel(8.5, 5),
            scale = 0.5
        },
      },
    }
    data.raw["assembling-machine"]["assembling-machine-2"].animation = {
      layers = {
        {
            filename = "__SingleColorTerrain_Redux__/graphics/entity/assembling-machine-2/hr-assembling-machine-2.png",
            priority = "high",
            width = 214,
            height = 218,
            frame_count = 32,
            line_length = 8,
            shift = util.by_pixel(0, 4),
            scale = 0.5
        },
        {
            filename = "__base__/graphics/entity/assembling-machine-2/hr-assembling-machine-2-shadow.png",
            priority = "high",
            width = 196,
            height = 163,
            frame_count = 32,
            line_length = 8,
            draw_as_shadow = true,
            shift = util.by_pixel(12, 4.75),
            scale = 0.5
        },
      },
    }
    data.raw["assembling-machine"]["assembling-machine-3"].animation = {
      layers = {
        {
            filename = "__SingleColorTerrain_Redux__/graphics/entity/assembling-machine-3/hr-assembling-machine-3.png",
            priority = "high",
            width = 214,
            height = 237,
            frame_count = 32,
            line_length = 8,
            shift = util.by_pixel(0, -0.75),
            scale = 0.5
        },
        {
            filename = "__base__/graphics/entity/assembling-machine-3/hr-assembling-machine-3-shadow.png",
            priority = "high",
            width = 260,
            height = 162,
            frame_count = 32,
            line_length = 8,
            draw_as_shadow = true,
            shift = util.by_pixel(28, 4),
            scale = 0.5
        },
      },
    }
end	  
	
if settings.startup["no-clouds"].value  then
	data.raw["utility-sprites"]["default"].clouds =
    {
      filename = "__core__/graphics/clouds.png",
      priority = "low",
      flags = { "linear-minification", "linear-magnification" },
      width = 1,
      height = 1,
      frame_count = 1
    }
	end

if settings.startup["white-stone"].value  then
    data.raw["tile"]["stone-path"].variants = {
      main = {
        {
          picture = "__SingleColorTerrain_Redux__/graphics/stone-path/stone-path-1.png",
          count = 16,
          size = 1,
          hr_version =
          {
            picture = "__SingleColorTerrain_Redux__/graphics/stone-path/hr-stone-path-1.png",
            count = 16,
            size = 1,
            scale = 0.5
          }
        },
        {
          picture = "__SingleColorTerrain_Redux__/graphics/stone-path/stone-path-2.png",
          count = 16,
          size = 2,
          probability = 0.39,
          hr_version =
          {
            picture = "__SingleColorTerrain_Redux__/graphics/stone-path/hr-stone-path-2.png",
            count = 16,
            size = 2,
            probability = 0.39,
            scale = 0.5
          }
        },
        {
          picture = "__SingleColorTerrain_Redux__/graphics/stone-path/stone-path-4.png",
          count = 16,
          size = 4,
          probability = 1,
          hr_version =
          {
            picture = "__SingleColorTerrain_Redux__/graphics/stone-path/hr-stone-path-4.png",
            count = 16,
            size = 4,
            probability = 1,
            scale = 0.5
          }
        }
      },
      transition = {
        overlay_layout = {
          inner_corner = {
            spritesheet  = "__SingleColorTerrain_Redux__/graphics/stone-path/hr-stone-path-inner-corner.png",
            count = 16,
            scale = 0.5,
            tile_height = 2
          },
          outer_corner = {
            spritesheet  = "__SingleColorTerrain_Redux__/graphics/stone-path/hr-stone-path-outer-corner.png",
            count = 8,
            scale = 0.5,
            tile_height = 2
          },
          side = {
            count = 16,
            spritesheet  = "__SingleColorTerrain_Redux__/graphics/stone-path/hr-stone-path-side.png",
            scale = 0.5,
            tile_height = 2
          },
          u_transition = {
            spritesheet  = "__SingleColorTerrain_Redux__/graphics/stone-path/hr-stone-path-u.png",
            count = 8,
            scale = 0.5,
            tile_height = 2
          },
          o_transition = {
            spritesheet  = "__SingleColorTerrain_Redux__/graphics/stone-path/hr-stone-path-o.png",
            count = 4,
            scale = 0.5
          }
        }
      }
    }
end
	
    
if settings.startup["white-concrete"].value  then
  data.raw["tile"]["concrete"].variants = {
    material_background = {
      picture = "__SingleColorTerrain_Redux__/graphics/concrete/hr-concrete.png",
      count = 8,
      scale = 0.5
    },
    transition = {
      mask_layout = {
        inner_corner = {
            spritesheet  = "__base__/graphics/terrain/concrete/concrete-inner-corner-mask.png",
            count = 16,
            scale = 0.5
        },      
        outer_corner = {
            spritesheet  = "__base__/graphics/terrain/concrete/concrete-outer-corner-mask.png",
            count = 8,
            scale = 0.5
        },
        side = {
            spritesheet  = "__base__/graphics/terrain/concrete/concrete-side-mask.png",
            count = 16,
            scale = 0.5
        },
        u_transition = {
            spritesheet  = "__base__/graphics/terrain/concrete/concrete-u-mask.png",
            count = 8,
            scale = 0.5
        },
        o_transition = {
            spritesheet  = "__base__/graphics/terrain/concrete/concrete-o-mask.png",
            count = 4,
            scale = 0.5
        }
      },
      overlay_layout = {
        inner_corner = {
          spritesheet  = "__SingleColorTerrain_Redux__/graphics/concrete/hr-concrete-inner-corner.png",
          count = 16,
          scale = 0.5
        },
        outer_corner = {
            spritesheet  = "__SingleColorTerrain_Redux__/graphics/concrete/hr-concrete-outer-corner.png",
            count = 8,
            scale = 0.5
        },
        side = {
            spritesheet  = "__SingleColorTerrain_Redux__/graphics/concrete/hr-concrete-side.png",
            count = 16,
            scale = 0.5
        },
        u_transition = {
            spritesheet  = "__SingleColorTerrain_Redux__/graphics/concrete/hr-concrete-u.png",
            count = 8,
            scale = 0.5
        },
        o_transition = {
            spritesheet  = "__SingleColorTerrain_Redux__/graphics/concrete/hr-concrete-o.png",
            count = 4,
            scale = 0.5
        }
      }
    }
  }
end
